version: '3.1'
services:
  web:
    image: mikesol/scalablehello_web:v3
    environment:
      - RAILS_ENV=production
      - RAILS_DATABASE_HOST=rails.cofykfiadir7.us-west-2.rds.amazonaws.com
      - RAILS_DATABASE_NAME=rails
      - RAILS_DATABASE_USERNAME=rails
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "80:3000"
