version: '3.1'
services:
  web:
    image: mikesol/scalablehello_web:v2
    environment:
      - RAILS_ENV=production
      - RAILS_DATABASE_HOST=rails.cofykfiadir7.us-west-2.rds.amazonaws.com
      - RAILS_DATABASE_NAME=rails
      - RAILS_DATABASE_USERNAME=rails
    secrets:
      - rails_database_password
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "80:3000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
secrets:
  rails_database_password:
    external: true
