# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a6f16ffa2b0b01d7a3a37250d4a056534623adadb798f8076c7f927c059812a87725e7bf27a38eb990d57442ee5fae0b1edcebbf6b7785da256e80b474b97e1

test:
  secret_key_base: 791b6db221d29c6ffefec57f960821a8a60a4c828b5d732de9a4cf08b0b2c9141acc2316828817eaec94c07c2307f69a0eef4571d8d2e684e4408f3f642d5f6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= if ENV['RAILS_ENV'] == 'production' then File.open("/run/secrets/rails_secret_key_base", "r") { |f| f.read } else '' end %>
